### ISSUE TITLE
Smooth corners on rectangles

### ISSUE THREAD

**Issue by pavsidhu** [wopian/smooth-corners#45]
If I set a div with the following CSS, I don't get the correct shape.

```css
.box {
  width: 200px;
  height: 100px;
  --smooth-corners: 4;
  mask-image: paint(smooth-corners);
  -webkit-mask-image: paint(smooth-corners);
  background: #d01257;
}
```

![image](https://user-images.githubusercontent.com/4911505/205058361-5498c8a4-536f-4927-a6a5-ee2b84439c74.png)

Does this only work with squares?
